name: Build Internt Speed Meter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify PyInstaller installation
      run: |
        python -m PyInstaller --version

    - name: Build executable
      run: |
        python -m PyInstaller --onefile --noconsole --icon=logo.ico --add-data "download_icon.png;." --add-data "upload_icon.png;." internet-speed-widget.py

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: internet-speed-widget
        path: dist/internet-speed-widget.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/internet-speed-widget.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}